[workspace]
resolver = "2"
members = [
    "crates/pensieve", # Pensieve lib
]

# Dependencies used by all/many crates
[workspace.dependencies]
# INTERNAL CRATES
pensieve = { path = "crates/pensieve" } # BCH Error Correction Code lib

# EXTENRAL CRATES (sort lexicographically)